### ISSUE TITLE
No module named 'django.core.urlresolvers' na django-master

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#428]
```
Traceback (most recent call last):

  File "/home/travis/build/watchdogpolska/poradnia/manage.py", line 10, in <module>

    execute_from_command_line(sys.argv)

  File "/home/travis/build/watchdogpolska/poradnia/.tox/py34-djmaster-coveralls/lib/python3.4/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line

    utility.execute()

  File "/home/travis/build/watchdogpolska/poradnia/.tox/py34-djmaster-coveralls/lib/python3.4/site-packages/django/core/management/__init__.py", line 347, in execute

    django.setup()

  File "/home/travis/build/watchdogpolska/poradnia/.tox/py34-djmaster-coveralls/lib/python3.4/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/home/travis/build/watchdogpolska/poradnia/.tox/py34-djmaster-coveralls/lib/python3.4/site-packages/django/apps/registry.py", line 112, in populate

    app_config.import_models()

  File "/home/travis/build/watchdogpolska/poradnia/.tox/py34-djmaster-coveralls/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models

    self.models_module = import_module(models_module_name)

  File "/home/travis/build/watchdogpolska/poradnia/.tox/py34-djmaster-coveralls/lib/python3.4/importlib/__init__.py", line 109, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import

  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load

  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 1129, in _exec

  File "<frozen importlib._bootstrap>", line 1471, in exec_module

  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed

  File "/home/travis/build/watchdogpolska/poradnia/poradnia/users/models.py", line 8, in <module>

    from django.core.urlresolvers import reverse

ImportError: No module named 'django.core.urlresolvers'
```

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m czy to aktualne?
