### ISSUE TITLE
Pobieranie e-maili stanęło

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#485]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django_mailbox/management/commands/getmail.py", line 24, in handle
    messages = mailbox.get_new_mail()
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django_mailbox/models.py", line 413, in get_new_mail
    msg = self.process_incoming_message(message)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django_mailbox/models.py", line 230, in process_incoming_message
    msg = self._process_message(message)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django_mailbox/models.py", line 351, in _process_message
    self._process_save_original_message(message, msg)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django_mailbox/models.py", line 403, in _process_save_original_message
    save=False
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django/db/models/fields/files.py", line 94, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/home/porady/releases/releases/20171214185419/env/lib/python3.5/site-packages/django/core/files/storage.py", line 355, in _save
    _file.write(chunk)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 5595: surrogates not allowed
```

Zalecam:

- przenieść e-mail do osobnego folderu (tymczasowo),
- naprawić kod, 
- wgrać aktualizacje,
- zaimportować wadliwy e-mail.

@mik-laj  ma dostep do skrzynki pocztowej, aby przenieść e-maile, a @kbiernat  ostatnio aktualizował kod.

**Comment by ad-m** [comment]
@kbiernat, zakomentowałem cronjoba.

**Comment by kbiernat** [comment]
przeniosłem maile do issue485, odkomentowałem crona

**Comment by kbiernat** [comment]
wrzuciłem zanonimizowany mail z prostym testem
https://github.com/watchdogpolska/poradnia/tree/issue/485

**Comment by ad-m** [comment]
To teraz trzeba naprawić import, skoro już wyizolowaliśmy przypadek testowy. Albo @mik-laj , albo @kbiernat , bo ja jeszcze nie pracuje dla MC. Widać, że test nie przechodzi tylko dla Python 3 https://travis-ci.org/watchdogpolska/poradnia/builds/318049495

**Comment by kbiernat** [comment]
jako że na py2 działa, odpaliłem pomyślnie getmail ze starego releasu aby mail nie czekał na rozwiązanie problemu.
INFO:poradnia.letters.models:Message #14466 registered in case #1418 as letter #22177
INFO:poradnia.letters.models:Message #14467 registered in case #1418 as letter #22178
Można na spokojnie opracować fix. Będzie to się wiązało bardziej z modyfikacją django-mailbox niż samej poradni.

**Comment by ad-m** [comment]
@kbiernat , dobry pomysł! Teraz trzeba naprawić kod importowania. W django-mailbox mam prawa do pisania w repozytorium, więc zgłoś tam poprawnie błąd, a najlepiej zrób PR to się tym zajmę.

**Comment by ad-m** [comment]
```
INFO:django_mailbox.management.commands.getmail:Gathering messages for main@porady.siecobywatelska.pl
Traceback (most recent call last):
  File "/home/porady/releases/current//src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django_mailbox/management/commands/getmail.py", line 24, in handle
    messages = mailbox.get_new_mail()
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django_mailbox/models.py", line 413, in get_new_mail
    msg = self.process_incoming_message(message)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django_mailbox/models.py", line 230, in process_incoming_message
    msg = self._process_message(message)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django_mailbox/models.py", line 351, in _process_message
    self._process_save_original_message(message, msg)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django_mailbox/models.py", line 403, in _process_save_original_message
    save=False
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django/db/models/fields/files.py", line 94, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/home/porady/releases/current/env/lib/python3.5/site-packages/django/core/files/storage.py", line 355, in _save
    _file.write(chunk)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcea' in position 5546: surrogates not allowed
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by kbiernat** [comment]
problem dotyczył tej samej sprawy, odpaliłem znowu z Py27 i odkomentowałem

**Comment by ad-m** [comment]
Trzeba albo naprawić ten kod, albo przywrócić PY27, bo to tak nie może
działać.

Wysłano z urządzenia mobilnego.

23.12.2017 18:39 "Krzysztof Biernat" <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
Padło znowu.

Wysłano z urządzenia mobilnego.

23.12.2017 18:47 <naczelnik@jawnosc.tk> napisał(a):

**Comment by kbiernat** [comment]
Wykonałem rollback.

**Comment by ad-m** [comment]
Dziękuję.

Wysłano z urządzenia mobilnego.

27.12.2017 13:35 "Krzysztof Biernat" <notifications@github.com> napisał(a):
