### ISSUE TITLE
Wyjątek po kliknięciu w link 'Nowa sprawa'

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/poradnia#496]
W logach supervisord pojawia się:
[2018-01-13 17:49:26 +0000] [8601] [DEBUG] GET /listy/
WARNING:root:Could not resolve form field 'email_registration'.
Traceback (most recent call last):
  File "/home/porady/releases/releases/20180110084256/env/local/lib/python2.7/site-packages/crispy_forms/utils.py", line 81, in render_field
    bound_field = form[field]
  File "/home/porady/releases/releases/20180110084256/env/local/lib/python2.7/site-packages/django/forms/forms.py", line 164, in __getitem__
    ', '.join(sorted(f for f in self.fields)),
KeyError: u"Key 'email_registration' not found in 'NewCaseForm'. Choices are: client, email, giodo, name, text."

Na froncie wszystko jest ok.

**Comment by AgnieszkaZdanowicz** [comment]
nie wiem, na czym polegał ten wyjątek - wydaje mi się, że nie było zgłaszanych takich błędów ostatnio

**Comment by ad-m** [comment]
Objawia się to tylko w logach. Nie mam pewności czy zostało uprzątnięte.

**Comment by PiotrIw** [comment]
aktualne, choć niegroźne - widzę to również w testach, trzeba przebudowac init formularzy, niemniej jednak crispy-forms przechodzą nad tym i wyświetlają formularz poprawnie

**Comment by PiotrIw** [comment]
naprawione w wersji 1.1.8
