### ISSUE TITLE
Naprawa budowy front-endu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia#536]
@mik-laj , 

- [ ] uprzejmie proszę o udokumentowanie budowy front-endu,
- [ ] stanowczo rekomenduje objęcie budowy front-endu testami.
- [ ] dopuszczam usunięcie z repozytorium skompilowanych plików front-endu, jeżeli powyższe zostanie wykonane.

**Comment by ad-m** [comment]
Wskazuje:
```
$ npm install (...)
Installed to /home/adas/Devel/poradnia/node_modules/node-sass/vendor/linux-x64-57/binding.node
npm WARN poradnia@0.1.0 No repository field.
npm WARN poradnia@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1024 packages in 114.13s
$ ./node_modules/.bin/gulp scss
module.js:549
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/home/adas/Devel/poradnia/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by ad-m** [comment]
@rwakulszowa , nie jestem front-endowy. Nie istnieje dokumentacja dla kompatybilnej wersji NodeJS. Ani poprzez Vagranta (odchodzimy od tego powoli), ani poprzez Dockerfile (docelowe).
